// <auto-generated />
namespace Mieli_Mielo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApllyAnnotationsToUtilisateur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApllyAnnotationsToUtilisateur));
        
        string IMigrationMetadata.Id
        {
            get { return "201810282320287_ApllyAnnotationsToUtilisateur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
