// <auto-generated />
namespace Mieli_Mielo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class confirmPassWord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confirmPassWord));
        
        string IMigrationMetadata.Id
        {
            get { return "201811141812178_confirmPassWord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
